esphome:
  name: ***
  friendly_name: ***

esp8266:
  board: esp01_1m

ota:
  - platform: esphome
    password: "***"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "***"
    password: "***"

captive_portal:

# Sends packets via uart to the Nice BUS T4 bus

external_components:
  - source:
      type: git
      url: https://github.com/ngem1/Nice_BusT4
    refresh: 0s
#  - source: my_components

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0

api:
  reboot_timeout: 0s
  encryption:
    key: "***"

  services:
# to send hex commands to the drive
  - service: raw_command
    variables:
        raw_cmd: string
    then:
      lambda: |-
         nice_cover -> NiceBusT4::send_raw_cmd(raw_cmd);

  - service: send_inf_command
    variables:
       to_addr: string
       whose: string
       command: string
       type_command: string
       next_data: string
       data_on: bool
       data_command: string
    then:
      lambda: |-
        nice_cover -> NiceBusT4::send_inf_cmd(to_addr, whose, command, type_command, next_data, data_on, data_command);

# sash length recognition
  - service: gate_length_recognition
    then:
      lambda: |-
         nice_cover -> NiceBusT4::set_mcu("0b","01");

# BlueBus device recognition
  - service: devices_recognition
    then:
      lambda: |-
         nice_cover -> NiceBusT4::set_mcu("0a","01");         

# closing force
  - service: closing_force
    variables:
      force: string
    then:
      lambda: |-
         nice_cover -> NiceBusT4::set_mcu("4b", force);         

# opening force
  - service: opening_force
    variables:
      force: string
    then:
      lambda: |-
         nice_cover -> NiceBusT4::set_mcu("4a", force);

web_server:
  port: 80
#  js_include: "www.js"
#  js_url: ""
#  version: 2  

# Buttons for sending commands
button:
  - platform: template
    name: Step by step
    id: sbs
    on_press:
      lambda: |-
           nice_cover -> NiceBusT4::send_cmd(bus_t4::SBS);

  - platform: template
    name: Input status
    id: in_stat
    on_press:
      lambda: |-
           nice_cover -> NiceBusT4::send_raw_cmd("55.0D.00.03.00.66.08.06.6B.04.D0.99.00.00.4D.0D");

#         nice_cover -> NiceBusT4::send_raw_cmd("55 0c 00 ff 00 66 01 05 9D 01 82 01 64 E6 0c");
# 55.0E.00.03.00.81.08.07.8D.04.0B.A9.00.01.01.A6.0E search for positions

  - platform: template
    name: Pedestrian opening 1
    id: p_opn1
    on_press:
      lambda: |-
         nice_cover -> NiceBusT4::send_cmd(bus_t4::P_OPN1);
                      
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::STOP);
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::OPEN);
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::CLOSE);
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::P_OPN2);
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::P_OPN3);
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::P_OPN4);
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::P_OPN5);
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::P_OPN6);
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::UNLK_OPN);  # Unlock and open
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::CLS_LOCK);  # Close and lock
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::UNLCK_CLS); # Unlock and Close
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::LOCK);      # Lock
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::UNLOCK);    # Unlock
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::HOST_SBS);  # Host SBS
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::HOST_OPN);  # Host Open
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::HOST_CLS);  # Host Close
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::SLAVE_SBS); # Slave SBS
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::SLAVE_OPN); # Slave Open
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::SLAVE_CLS); # Slave Close
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::AUTO_ON);   # Auto-opening
#         nice_cover -> NiceBusT4::send_cmd(bus_t4::AUTO_OFF);  # Auto-closing

cover:
- platform: bus_t4
  name: "Nice Cover"
  device_class: gate
  id: nice_cover
  
#  address: 0x0003            # drive address
#  use_address: 0x0081        # gateway address


# We are working with the OXI receiver.

# disable automatic gate closing if necessary for loading and unloading operations
switch:
  - platform: template
    name: "Auto-close"
    id: autoclose
    restore_mode: DISABLED
#    optimistic: true
    lambda: |-
      if (nice_cover -> NiceBusT4::autocls_flag) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      lambda: |-
        nice_cover -> NiceBusT4::send_inf_cmd("0003", "04", "80", "a9", "00", true, "01");
        nice_cover -> NiceBusT4::send_inf_cmd("0003", "04", "84", "a9", "00", true, "01");
        nice_cover -> NiceBusT4::send_inf_cmd("0003", "04", "80", "99", "00", true, "01");
        nice_cover -> NiceBusT4::send_inf_cmd("0003", "04", "84", "99", "00", true, "01");                
    turn_off_action:
      lambda: |-
        nice_cover -> NiceBusT4::send_inf_cmd("0003", "04", "80", "a9", "00", true, "00");
        nice_cover -> NiceBusT4::send_inf_cmd("0003", "04", "84", "a9", "00", true, "00");
        nice_cover -> NiceBusT4::send_inf_cmd("0003", "04", "80", "99", "00", true, "01");
        nice_cover -> NiceBusT4::send_inf_cmd("0003", "04", "84", "99", "00", true, "01");                        


              
#script:
#  - id: send_cmd
#    then:
#      - switch.turn_on: my_switch
#      - delay: 1s
#      - switch.turn_off: my_switch              
